name: translations

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    paths:
      - 'text/*'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'text/*'
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v3.1.4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install jsonschema

      - name: Run JSON validation
        run: |
          python3 .ci/validate.py text/backup.json .ci/backup-schema.json
          python3 .ci/validate.py text/change-details.json .ci/change-details-schema.json
          python3 .ci/validate.py text/check-vps.json .ci/check-vps-schema.json
          python3 .ci/validate.py text/install.json .ci/install-schema.json
          python3 .ci/validate.py text/migrate.json .ci/migrate-schema.json
          python3 .ci/validate.py text/status.json .ci/status-schema.json
          python3 .ci/validate.py text/tool.json .ci/tool-schema.json
          python3 .ci/validate.py text/update.json .ci/update-schema.json
